name: Send to S3

on:
 push:
    branches: [ main ]

jobs:
 deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create hello_world.txt
      run: echo "Hello, World! Current time is $(date)" > hello_world.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Copy hello_world.txt to S3
      run: |
        aws s3 cp hello_world.txt s3://scraper-meli
